name: jmwbz
favicon: null
layout_spectrum: 0
typography_spectrum: 0.66179
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020224'
    - '#c2c2a7'
    - '#e9e9c7'
    - '#56495a'
    - '#838967'
  brandStrength: 0.875
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
