name: jmwbz
favicon: null
layout_spectrum: 0.6085610671434551
typography_spectrum: 0.3181360955350101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3681914934422821
  lightness: 0.8294510589912534
  saturation: 0.40963261714205146
  rhythmicContrast: 0.25759309343993664
purpose: []
